# Defines the services

version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db: 
    image: "postgres:12"
    environment:
      POSTGRES_DB: evalxai_db
      POSTGRES_USER: evalxai_user
      POSTGRES_PASSWORD: password